version: '3.9'

services:
  db:
    build: .
    image: knutra/mssqldocker:v2019
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: TicketDB
      MSSQL_USER: TicketAPI
      MSSQL_PASSWORD: Pa5$w0rd
    ports:
      - "1433:1433"
    container_name: mssqldev
